### ISSUE TITLE
The sample site does not load any documents while clicking on ScanDocuments button in the UI.

### ISSUE THREAD

**Issue by sangareswaran** [yushulx/dynamsoft-service-REST-API#1]
The UI is loaded
Clicking on GetDevices button loads the devices in the dropdown
Clicking on ScanDocuments does not load anything.

![image](https://github.com/yushulx/dynamsoft-service-REST-API/assets/15410391/2105cf0b-a5a6-4c45-8b8e-3f00b674b0f9)
![issue](https://github.com/yushulx/dynamsoft-service-REST-API/assets/15410391/d8d6b2bf-c57a-4f32-b106-5a6ca506feca)

**Comment by yushulx** [comment]
@sangareswaran have you set a valid license key?
